[package]
name = "vexplorer-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
fuzzy-matcher = "0.3.7"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
rayon = "1.5.1"